apiVersion: v2
name: relution
description: Install Relution in your Kubernetes cluster using Helm.
icon: https://relution.io/icons/icon-512x512.png

type: application

version: 0.0.11

appVersion: "5.14.1"
