{{- if .Values.relution.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "relution.fullname" . }}-secrets
  labels:
    {{- include "relution.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.relution.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{ end -}}
{{- end }}
